name = Student Org
description = Page layout for uiowa_student_org Omega subtheme.
preview = preview.png
template = student-org-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[hero]           = Hero
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/student_org/student_org.layout.css
